version: '3.8'

services:
  backend:
    build: ./backend
    container_name: book-management-backend
    restart: unless-stopped
    ports:
      - "5555:5555"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    networks:
      - book-management-network

  frontend:
    build: ./frontend
    container_name: book-management-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - book-management-network

networks:
  book-management-network:
    driver: bridge 