version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5555:5555"  # Match the PORT from .env
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/books-collection
      - PORT=5555  # Added PORT environment variable

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: