version: '3.8'

services:
  backend:
    build: ./backend
    container_name: book-management-backend
    restart: unless-stopped
    ports:
      - "5002:5555"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - uploads_data:/app/uploads
    env_file:
      - ./backend/.env
    networks:
      - book-management-network

  frontend:
    build: ./frontend
    container_name: book-management-frontend
    restart: unless-stopped
    ports:
      - "82:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/code
    networks:
      - book-management-network

networks:
  book-management-network:
    driver: bridge

volumes:
  uploads_data:
    driver: local 
    
