version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5555:5555"
    environment:
      - MONGODB_URI=mongodb+srv://hafsahphone3:eE3yvGZ2Ax_qH4y@book-store-mern.qmpya.mongodb.net/books-collection?retryWrites=true&w=majority&appName=Book-Store-Mern
      - PORT=5555

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5555
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules